port: 8080

spring:
  application:
    name: drug

    datasource:
      url: jdbc:sqlserver://MSWISLOC-CK9938;databaseName=drug;encrypt=true;trustServerCertificate=trueertificate=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true